### ISSUE TITLE
Usando o PTT5 para resumir textos ("summarize:")

### ISSUE THREAD

**Issue by jlgondimDSTI** [unicamp-dl/PTT5#12]
Estou tentando usar o PTT5 para resumir textos, mas o modelo produz como saída o texto fornecido na entrada, inclusive com o comando inicial "summarize: ".

Estou fazendo algo errado ou o PTT5 não disponibiliza esta funcionalidade? Segue abaixo o meu código.

MODEL_NAME = 'unicamp-dl/ptt5-base-portuguese-vocab'
tokenizer = T5Tokenizer.from_pretrained(MODEL_NAME)
model = T5ForConditionalGeneration.from_pretrained(MODEL_NAME)

preprocess_text = text.strip().replace("\n","")
t5_prepared_Text = "summarize: "+preprocess_text

tokenized_text = tokenizer.encode(t5_prepared_Text, return_tensors="pt").to(device)

summary_ids = model.generate(tokenized_text,
                                    num_beams=4,
                                    no_repeat_ngram_size=2,
                                    min_length=30,
                                    max_length=100,
                                    early_stopping=True)

output = tokenizer.decode(summary_ids[0], skip_special_tokens=True)

print ("\n\nSummarized text: \n",output)

**Comment by marcospiau** [comment]
Olá, @jlgondimDSTI.

Para conseguir usar o PTT5 para sumarização de textos, você precisa primeiro realizar um treinamento específico ("ajuste fino") para essa tarefa específica. Sem essa etapa de ajuste fino para a tarefa de sumarização, serão gerados textos parecidos como que você obteve.
