### ISSUE TITLE
Usando o PTT5 com ASSIN e HuggingFace

### ISSUE THREAD

**Issue by alinepaes** [unicamp-dl/PTT5#33]
Olá, obrigada pelo trabalho de vocês.
Estou tentando experimentar o PTT5 com a tarefa de similaridade semântica conforme o ASSIN, usando o HuggingFace e as instruções do artigo.

Entretanto, a saída sempre é a mesma que a entrada. Alguma dica do que posso estar fazendo de errado? Já experimentei com algumas variações do texto de entrada, mas o efeito é o mesmo. O mesmo acontece com a tarefa de reconhecimento de entidades nomeadas. Obrigada.

Código:

from transformers import T5Tokenizer
from transformers import T5Model, T5ForConditionalGeneration

model_name = 'unicamp-dl/ptt5-base-portuguese-vocab'

tokenizer = T5Tokenizer.from_pretrained(model_name)
model = T5ForConditionalGeneration.from_pretrained(model_name)

#NER artigo: Recognize Entities: [S][eos]
#text = "Recognize Entities: Maria vive na baixada."
#ASSIN artigo: ASSIN sentence1: [S1][eos]sentence2: [S2][eos]
text = "ASSIN: sentence1: Minha tia está feliz.sentence2: Meu tio está feliz." 

input_ids = tokenizer(text, return_tensors="pt").input_ids
outputs = model.generate(input_ids)
print(tokenizer.decode(outputs[0], skip_special_tokens=True))

**Comment by rodrigonogueira4** [comment]
Oi Aline, o modelo que você está usando não foi treinado no ASSIN 2, ele apenas foi treinado em textos em portugues. Assim, você precisa treina-lo no ASSIN 2 para que ele produza as saidas corretas.

**Comment by alinepaes** [comment]
Obrigada, Rodrigo.
Então esse modelo não é o mencionado no artigo? O modelo mencionado no artigo está disponível?

**Comment by marcospiau** [comment]
Oi Aline, nós não disponibilizamos os modelos treinados nas tarefas _downstream_ (ASSIN2 ou NER), apenas os modelos treinados em português usando pré-treinamento semi-supervisionado foram disponibilizados. Sem o ajuste fino nas tarefas _downstream_, os modelos geram esses textos "constantes" que você observou.

**Comment by alinepaes** [comment]
Oi Marcos, muito obrigada! Já é de imensa ajuda :)
